config/routes.rb
Rails.application.routes.draw do
  get 'hello', to: 'welcome#index'
  resources 'blogs'
  resources 'users'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def list_blog
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    @blog.update blogs_params
    redirect_to @blog
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new blogs_params
    @blog.save
    redirect_to @blog
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private
    def blogs_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params['id'])
  end

  def edit
    @user = User.find(params['id'])
  end

  def update
    user = User.find(params['id'])
    user.update users_params
    redirect_to user
  end

  def new
    @user = User.new
  end

  def create
    user = User.new users_params
    user.save

    redirect_to user
  end

  def destroy
    user = User.find(params['id'])
    user.destroy

    redirect_to users_path
  end

  private
    def users_params
      params.require(:user).permit(:name, :age)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.slim
= form_with model: blog, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :content
    = f.text_area :content
  = f.submit "Submit"

app/views/blogs/edit.slim
h1 Edit blog #{@blog.title}
= render 'form', blog: @blog

div Jello

app/views/blogs/index.slim
p
  a href="#{new_blog_path}" Create blog
table
  tr
    th id
    th title
    th content
    th action
  - @blogs.each do |blog|
    tr
      td = blog.id
      td = blog.title
      td = blog.content
      td
        a href="#{blog_path blog}" Show
        span  |
        a href="#{edit_blog_path blog}"  Edit 
        span |
        = link_to "Delete", blog_path(blog), method: :delete, data: {confirm: 'Are you sure?'}

app/views/blogs/new.slim
h1 Create blog
= render 'form', blog: @blog

app/views/blogs/show.slim
h2 #{@blog.title}
p #{@blog.content}

a href="#{blogs_path}" Back

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.slim
h1 Edit User ##{@user.id}

= form_with model: @user, local: true do |f|
  div
    label Name
    = f.text_field :name
  br/
  div 
    label Age
    = f.text_field :age
  br/
  div
    button Submit

a href="/users" Back

app/views/users/index.slim
p 
  | Create new user: 
  a href="/users/new" Create
table
  tr
    th id
    th name
    th age
    th action
  - @users.each do |user|
    tr
      td #{user.id}
      td #{user.name}
      td #{user.age}
      td
        a href="/users/#{user.id}" Show
        span | 
        a href="/users/#{user.id}/edit"  Edit
        

app/views/users/new.slim
h1 Hello

= form_with model: @user, local: true do |f|
  div
    label Name
    = f.text_field :name
  br/
  div 
    label Age
    = f.text_field :age
  br/
  div
    button Submit

a href="/users" Back

app/views/users/show.slim
h1 Show user which have id #{@user.id}

p #{@user.name}
p #{@user.age}

p
  = link_to "Delete", user_path(@user), method: :delete, data: {confirm: 'Are you sure?'}
p
  a href="/users" Back

app/views/welcome/index.html.erb
<h1>Welcome!</h1>